# Default PostgreSQL for easily deploying on heroku

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db_development
  
test:
  <<: *default
  database: db_test

production:
  <<: *default
  database: ddb_production
